/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'writer-runs': WriterRun;
    'blog-posts': BlogPost;
    'blog-post-redirects': BlogPostRedirect;
    'content-pages': ContentPage;
    categories: Category;
    authors: Author;
    'writer-sources': WriterSource;
    'writer-stage-executions': WriterStageExecution;
    'writer-jobs': WriterJob;
    'writer-artifacts': WriterArtifact;
    'writer-trace-events': WriterTraceEvent;
    'writer-remote-files': WriterRemoteFile;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'writer-runs': WriterRunsSelect<false> | WriterRunsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-post-redirects': BlogPostRedirectsSelect<false> | BlogPostRedirectsSelect<true>;
    'content-pages': ContentPagesSelect<false> | ContentPagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'writer-sources': WriterSourcesSelect<false> | WriterSourcesSelect<true>;
    'writer-stage-executions': WriterStageExecutionsSelect<false> | WriterStageExecutionsSelect<true>;
    'writer-jobs': WriterJobsSelect<false> | WriterJobsSelect<true>;
    'writer-artifacts': WriterArtifactsSelect<false> | WriterArtifactsSelect<true>;
    'writer-trace-events': WriterTraceEventsSelect<false> | WriterTraceEventsSelect<true>;
    'writer-remote-files': WriterRemoteFilesSelect<false> | WriterRemoteFilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ai-writer-settings': AiWriterSetting;
  };
  globalsSelect: {
    'ai-writer-settings': AiWriterSettingsSelect<false> | AiWriterSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-runs".
 */
export interface WriterRun {
  id: number;
  /**
   * Primary keyword or topic the article should target.
   */
  targetKeyword?: string | null;
  /**
   * Original source URL the workflow should analyze before discovering competitors.
   */
  sourceUrl?: string | null;
  normalizedSourceUrl: string;
  writeUserPrompt?: string | null;
  status: 'draft' | 'discovering' | 'awaiting_selection' | 'awaiting_user' | 'processing' | 'completed' | 'failed';
  currentStage?:
    | (
        | 'discover_serp'
        | 'source_selection'
        | 'convert_markdown'
        | 'extract_blocks'
        | 'compute_target_word_count'
        | 'build_factpack'
        | 'brief'
        | 'validate'
        | 'write'
        | 'check'
      )
    | null;
  originalWordCount?: number | null;
  targetWordCount?: number | null;
  errorMessage?: string | null;
  createdDraft?: (number | null) | BlogPost;
  automationLeaseOwner?: string | null;
  automationLeaseToken?: string | null;
  automationLeaseExpiresAt?: string | null;
  automationHeartbeatAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  prismicId?: string | null;
  uid: string;
  uidLocaleKey?: string | null;
  lang: 'en';
  title: string;
  excerpt?: string | null;
  seoDescription?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categoryRef?: (number | null) | Category;
  author?: (number | null) | Author;
  heroImageMedia?: (number | null) | Media;
  publishedAt?: string | null;
  featured?: boolean | null;
  category?: string | null;
  categorySlug?: string | null;
  heroImage?: {
    url?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
  };
  bodyHtml?: string | null;
  bodyText?: string | null;
  readTime?: string | null;
  firstPublishedAt?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  prismicId?: string | null;
  lang: 'en';
  name: string;
  slug: string;
  slugLocaleKey?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  prismicId?: string | null;
  uid: string;
  slugLocaleKey?: string | null;
  slug: string;
  lang: 'en';
  name: string;
  position?: string | null;
  role?: string | null;
  bio?: string | null;
  shortBio?: string | null;
  avatarMedia?: (number | null) | Media;
  avatar?: {
    url?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
  };
  handle?: string | null;
  linkedinUrl?: string | null;
  githubUrl?: string | null;
  credentials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  knowsAbout?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  firstPublishedAt?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  sourceUrl?: string | null;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-post-redirects".
 */
export interface BlogPostRedirect {
  id: number;
  fromUid: string;
  toUid: string;
  lang: 'en';
  redirectKey?: string | null;
  post?: (number | null) | BlogPost;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pages".
 */
export interface ContentPage {
  id: number;
  prismicId?: string | null;
  uid: string;
  uidLocaleKey?: string | null;
  lang: 'en';
  /**
   * Page title shown to editors and downstream consumers.
   */
  title: string;
  /**
   * Primary page content editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seoDescription?: string | null;
  contentHtml?: string | null;
  firstPublishedAt?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-sources".
 */
export interface WriterSource {
  id: number;
  run: number | WriterRun;
  role: 'original' | 'competitor';
  url: string;
  normalizedUrl: string;
  title?: string | null;
  metaDescription?: string | null;
  serpPosition?: number | null;
  snippet?: string | null;
  selected?: boolean | null;
  fetchStatus: 'pending' | 'fetching' | 'completed' | 'failed';
  fetchError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-stage-executions".
 */
export interface WriterStageExecution {
  id: number;
  run: number | WriterRun;
  stageKey:
    | 'discover_serp'
    | 'source_selection'
    | 'convert_markdown'
    | 'extract_blocks'
    | 'compute_target_word_count'
    | 'build_factpack'
    | 'brief'
    | 'validate'
    | 'write'
    | 'check';
  status: 'queued' | 'running' | 'awaiting_user' | 'completed' | 'failed';
  inputPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorText?: string | null;
  retryCount?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-jobs".
 */
export interface WriterJob {
  id: number;
  run: number | WriterRun;
  stageKey:
    | 'discover_serp'
    | 'source_selection'
    | 'convert_markdown'
    | 'extract_blocks'
    | 'compute_target_word_count'
    | 'build_factpack'
    | 'brief'
    | 'validate'
    | 'write'
    | 'check';
  kind: 'brief.generate' | 'validate.run' | 'write.generate' | 'check.audit' | 'check.revise';
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';
  source?: (number | null) | WriterSource;
  requestPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  responsePayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorText?: string | null;
  leaseOwner?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  leaseHeartbeatAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-artifacts".
 */
export interface WriterArtifact {
  id: number;
  run: number | WriterRun;
  source?: (number | null) | WriterSource;
  artifactType:
    | 'serp'
    | 'serp_raw'
    | 'raw_html'
    | 'markdown'
    | 'blocks'
    | 'factpack_json'
    | 'factpack_md'
    | 'brief_json'
    | 'brief_raw_json'
    | 'finalized_brief_json'
    | 'review_log_json'
    | 'article_draft_md'
    | 'failing_list_md'
    | 'check_report_json'
    | 'article_revision_richtext_json'
    | 'article_revision_md'
    | 'debug_output';
  artifactRole: 'model_input' | 'model_output_raw' | 'model_output_normalized' | 'review' | 'derived';
  schemaName?: string | null;
  schemaVersion?: string | null;
  sha256?: string | null;
  producedByJob?: (number | null) | WriterJob;
  supersedesArtifact?: (number | null) | WriterArtifact;
  mimeType: string;
  filename: string;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-trace-events".
 */
export interface WriterTraceEvent {
  id: number;
  run: number | WriterRun;
  stageKey?:
    | (
        | 'discover_serp'
        | 'source_selection'
        | 'convert_markdown'
        | 'extract_blocks'
        | 'compute_target_word_count'
        | 'build_factpack'
        | 'brief'
        | 'validate'
        | 'write'
        | 'check'
      )
    | null;
  source?: (number | null) | WriterSource;
  provider: 'user' | 'brightdata' | 'fetch' | 'anthropic' | 'openai' | 'local';
  eventType: string;
  status: 'completed' | 'failed' | 'running';
  requestPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  responsePayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorText?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-remote-files".
 */
export interface WriterRemoteFile {
  id: number;
  run: number | WriterRun;
  artifact?: (number | null) | WriterArtifact;
  source?: (number | null) | WriterSource;
  provider: string;
  fileId: string;
  artifactHash: string;
  status: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorText?: string | null;
  lastUsedAt?: string | null;
  deleteAttemptedAt?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'writer-runs';
        value: number | WriterRun;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-post-redirects';
        value: number | BlogPostRedirect;
      } | null)
    | ({
        relationTo: 'content-pages';
        value: number | ContentPage;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'writer-sources';
        value: number | WriterSource;
      } | null)
    | ({
        relationTo: 'writer-stage-executions';
        value: number | WriterStageExecution;
      } | null)
    | ({
        relationTo: 'writer-jobs';
        value: number | WriterJob;
      } | null)
    | ({
        relationTo: 'writer-artifacts';
        value: number | WriterArtifact;
      } | null)
    | ({
        relationTo: 'writer-trace-events';
        value: number | WriterTraceEvent;
      } | null)
    | ({
        relationTo: 'writer-remote-files';
        value: number | WriterRemoteFile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-runs_select".
 */
export interface WriterRunsSelect<T extends boolean = true> {
  targetKeyword?: T;
  sourceUrl?: T;
  normalizedSourceUrl?: T;
  writeUserPrompt?: T;
  status?: T;
  currentStage?: T;
  originalWordCount?: T;
  targetWordCount?: T;
  errorMessage?: T;
  createdDraft?: T;
  automationLeaseOwner?: T;
  automationLeaseToken?: T;
  automationLeaseExpiresAt?: T;
  automationHeartbeatAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  prismicId?: T;
  uid?: T;
  uidLocaleKey?: T;
  lang?: T;
  title?: T;
  excerpt?: T;
  seoDescription?: T;
  body?: T;
  categoryRef?: T;
  author?: T;
  heroImageMedia?: T;
  publishedAt?: T;
  featured?: T;
  category?: T;
  categorySlug?: T;
  heroImage?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
      };
  bodyHtml?: T;
  bodyText?: T;
  readTime?: T;
  firstPublishedAt?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-post-redirects_select".
 */
export interface BlogPostRedirectsSelect<T extends boolean = true> {
  fromUid?: T;
  toUid?: T;
  lang?: T;
  redirectKey?: T;
  post?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pages_select".
 */
export interface ContentPagesSelect<T extends boolean = true> {
  prismicId?: T;
  uid?: T;
  uidLocaleKey?: T;
  lang?: T;
  title?: T;
  content?: T;
  seoDescription?: T;
  contentHtml?: T;
  firstPublishedAt?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  prismicId?: T;
  lang?: T;
  name?: T;
  slug?: T;
  slugLocaleKey?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  prismicId?: T;
  uid?: T;
  slugLocaleKey?: T;
  slug?: T;
  lang?: T;
  name?: T;
  position?: T;
  role?: T;
  bio?: T;
  shortBio?: T;
  avatarMedia?: T;
  avatar?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
      };
  handle?: T;
  linkedinUrl?: T;
  githubUrl?: T;
  credentials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  knowsAbout?:
    | T
    | {
        value?: T;
        id?: T;
      };
  firstPublishedAt?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-sources_select".
 */
export interface WriterSourcesSelect<T extends boolean = true> {
  run?: T;
  role?: T;
  url?: T;
  normalizedUrl?: T;
  title?: T;
  metaDescription?: T;
  serpPosition?: T;
  snippet?: T;
  selected?: T;
  fetchStatus?: T;
  fetchError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-stage-executions_select".
 */
export interface WriterStageExecutionsSelect<T extends boolean = true> {
  run?: T;
  stageKey?: T;
  status?: T;
  inputPayload?: T;
  outputPayload?: T;
  errorText?: T;
  retryCount?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-jobs_select".
 */
export interface WriterJobsSelect<T extends boolean = true> {
  run?: T;
  stageKey?: T;
  kind?: T;
  status?: T;
  source?: T;
  requestPayload?: T;
  responsePayload?: T;
  errorText?: T;
  leaseOwner?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  leaseHeartbeatAt?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-artifacts_select".
 */
export interface WriterArtifactsSelect<T extends boolean = true> {
  run?: T;
  source?: T;
  artifactType?: T;
  artifactRole?: T;
  schemaName?: T;
  schemaVersion?: T;
  sha256?: T;
  producedByJob?: T;
  supersedesArtifact?: T;
  mimeType?: T;
  filename?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-trace-events_select".
 */
export interface WriterTraceEventsSelect<T extends boolean = true> {
  run?: T;
  stageKey?: T;
  source?: T;
  provider?: T;
  eventType?: T;
  status?: T;
  requestPayload?: T;
  responsePayload?: T;
  errorText?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writer-remote-files_select".
 */
export interface WriterRemoteFilesSelect<T extends boolean = true> {
  run?: T;
  artifact?: T;
  source?: T;
  provider?: T;
  fileId?: T;
  artifactHash?: T;
  status?: T;
  metadata?: T;
  errorText?: T;
  lastUsedAt?: T;
  deleteAttemptedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  sourceUrl?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-writer-settings".
 */
export interface AiWriterSetting {
  id: number;
  provider: 'anthropic' | 'openai';
  anthropicModel?:
    | (
        | 'claude-opus-4-7'
        | 'claude-opus-4-1-20250805'
        | 'claude-opus-4-20250514'
        | 'claude-sonnet-4-20250514'
        | 'claude-3-7-sonnet-20250219'
      )
    | null;
  openaiModel?:
    | (
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5.2'
        | 'gpt-5.1'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-4.1'
      )
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-writer-settings_select".
 */
export interface AiWriterSettingsSelect<T extends boolean = true> {
  provider?: T;
  anthropicModel?: T;
  openaiModel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}