version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      payload:
        patterns:
          - payload
          - "@payloadcms/*"
      next:
        patterns:
          - next
          - eslint-config-next
  - package-ecosystem: composer
    directory: /packages/laravel
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
