import { DEFAULT_BROWSER_VERSION_POLICY } from "@repo/core/browser-versions"

export const BROWSER_VERSIONS_PUBLIC_PACKAGE_NAME = "@gatekeepr/browser-versions"
export const BROWSER_VERSIONS_PUBLIC_REPOSITORY = "gtkppr/browser-versions"

const PACKAGE_FILES = [
	"index.js",
	"README.md",
	"browser-versions.json",
	"browser-versions.min.json",
	"browser-versions.txt"
]

function ensureList(values, requiredValues) {
	const nextValues = Array.isArray(values) ? [...values] : []
	for(const value of requiredValues) {
		if(nextValues.includes(value)) continue
		nextValues.push(value)
	}
	return nextValues
}

function getBrowserEntries(dataset) {
	return Object.entries(dataset?.browsers || {})
		.sort(([left], [right]) => left.localeCompare(right))
}

export function createBrowserVersionsTxt(dataset) {
	const rows = getBrowserEntries(dataset)
		.map(([key, browser]) => [
			key,
			browser.name || key,
			browser.currentVersion || browser.latestVersion,
			browser.currentMajor ?? browser.latestMajor,
			browser.sources?.currentVersion?.source || browser.source,
			browser.sources?.currentVersion?.sourceUrl || browser.sourceUrl,
			browser.sources?.eol?.source || "",
			browser.sources?.eol?.sourceUrl || "",
			dataset?.policy?.assessment?.type || ""
		].join("\t"))
	return `${rows.join("\n")}${rows.length ? "\n" : ""}`
}

export function buildBrowserVersionsIndexSource() {
	return `import { createRequire } from "node:module"

const require = createRequire(import.meta.url)
const dataset = require("./browser-versions.json")
const browsers = dataset.browsers || {}

function normalizeBrowserKey(value = "") {
\treturn String(value || "").trim().toLowerCase()
}

export function getBrowser(key = "") {
\treturn browsers[normalizeBrowserKey(key)] || null
}

export function getLatestBrowserVersion(key = "") {
\treturn getBrowser(key)?.latestVersion || null
}

export function getCurrentBrowserVersion(key = "") {
\treturn getBrowser(key)?.currentVersion || getLatestBrowserVersion(key)
}

export function getLatestBrowserMajor(key = "") {
\treturn getBrowser(key)?.latestMajor || null
}

export function getCurrentBrowserMajor(key = "") {
\treturn getBrowser(key)?.currentMajor ?? getLatestBrowserMajor(key)
}

export { dataset, browsers }
export default dataset
`
}

export function buildBrowserVersionsReadme(dataset, {
	packageName = BROWSER_VERSIONS_PUBLIC_PACKAGE_NAME,
	repository = BROWSER_VERSIONS_PUBLIC_REPOSITORY
} = {}) {
	const browserRows = getBrowserEntries(dataset)
		.map(([key, browser]) => `| ${key} | ${browser.name} | ${browser.currentVersion || browser.latestVersion} | ${browser.currentMajor ?? browser.latestMajor} | ${browser.sources?.currentVersion?.source || browser.source} | ${browser.sources?.eol?.source || "-"} |`)
		.join("\n")
	return `# Browser Versions

Daily browser-version dataset generated by Gatekeepr.

## Installation

\`\`\`shell
npm install github:${repository}
\`\`\`

## Usage

\`\`\`javascript
import dataset, { getCurrentBrowserVersion } from "${packageName}"

console.log(getCurrentBrowserVersion("chrome"))
console.log(dataset.browsers.chrome.sources.currentVersion.sourceUrl)
console.log(dataset.browsers.firefox.currentMajor)
\`\`\`

## Files

- \`browser-versions.json\`: formatted machine-readable dataset
- \`browser-versions.min.json\`: compact machine-readable dataset
- \`browser-versions.txt\`: tab-delimited text file with browser key, name, current version, current major, current-version source, current-version source URL, vendor EOL source, vendor EOL source URL, and Gatekeepr assessment policy type

## Current Versions

| Key | Browser | Current Version | Current Major | Current Version Source | Vendor EOL Source |
| --- | --- | --- | --- | --- | --- |
${browserRows}

## Policy

Gatekeepr does not currently publish vendor EOL data for these browsers. The API classifies outdated and unsupported
browser claims with an internal major-version lag heuristic.

- Allowed major lag: ${dataset?.policy?.allowedMajorLag ?? DEFAULT_BROWSER_VERSION_POLICY.allowedMajorLag}
- Outdated major lag: ${dataset?.policy?.outdatedMajorLag ?? DEFAULT_BROWSER_VERSION_POLICY.outdatedMajorLag}
- Unsupported major lag: ${dataset?.policy?.unsupportedMajorLag ?? DEFAULT_BROWSER_VERSION_POLICY.unsupportedMajorLag}
- Suspicious future major lag: ${dataset?.policy?.maxFutureMajorLag ?? DEFAULT_BROWSER_VERSION_POLICY.maxFutureMajorLag}
- Assessment policy type: ${dataset?.policy?.assessment?.type || "major-version-lag-heuristic"}

Generated at: ${dataset?.generatedAt || "-"}

## About

**${packageName}** is maintained by [Gatekeepr](https://gatekeepr.io), a privacy-first API that blocks fake users and platform abuse by analyzing emails, IPs, domains, and user agents in real time.
`
}

export function shapeBrowserVersionsPackageJson(packageJson = {}, {
	version = packageJson?.version || "0.0.0",
	packageName = BROWSER_VERSIONS_PUBLIC_PACKAGE_NAME,
	repository = BROWSER_VERSIONS_PUBLIC_REPOSITORY
} = {}) {
	return {
		...packageJson,
		name: packageName,
		version,
		repository: packageJson?.repository || {
			type: "git",
			url: `git+https://github.com/${repository}.git`
		},
		type: "module",
		main: "index.js",
		exports: {
			".": "./index.js",
			"./browser-versions.json": "./browser-versions.json",
			"./browser-versions.min.json": "./browser-versions.min.json",
			"./browser-versions.txt": "./browser-versions.txt"
		},
		files: ensureList(packageJson?.files, PACKAGE_FILES)
	}
}

export function createBrowserVersionsPackageArtifacts(dataset, {
	packageJson = {},
	version = packageJson?.version || "0.0.0",
	packageName = BROWSER_VERSIONS_PUBLIC_PACKAGE_NAME,
	repository = BROWSER_VERSIONS_PUBLIC_REPOSITORY
} = {}) {
	return {
		browserVersionsJson: `${JSON.stringify(dataset, null, 2)}\n`,
		browserVersionsMinJson: `${JSON.stringify(dataset)}\n`,
		browserVersionsTxt: createBrowserVersionsTxt(dataset),
		indexJs: buildBrowserVersionsIndexSource(),
		readme: buildBrowserVersionsReadme(dataset, { packageName, repository }),
		packageJson: `${JSON.stringify(shapeBrowserVersionsPackageJson(packageJson, {
			version,
			packageName,
			repository
		}), null, 2)}\n`
	}
}
